Oficina_codeFirst/Controllers/AtendimentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Oficina_codeFirst.Models;

namespace Oficina_codeFirst.Controllers
{
    public class AtendimentoController : BaseController
    {
        private OficinaContext db = new OficinaContext();

        // GET: /Atendimento/
        public ActionResult Index()
        {
            var atendimentos = db.Atendimentos.Include(a => a.Carro).Include(a => a.Fatura);
            return View(atendimentos.ToList());
        }

        // GET: /Atendimento/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Atendimento atendimento = db.Atendimentos.Include(a => a.Fatura).Include(a => a.Carro).FirstOrDefault(a => a.Oid == id);
            if (atendimento == null)
            {
                return HttpNotFound();
            }
            return View(atendimento);
        }

        // GET: /Atendimento/Create
        public ActionResult Create()
        {
            ViewBag.CarroOid = new SelectList(db.Carros, "Oid", "Placa");
            ViewBag.Oid = new SelectList(db.Fatura, "Oid", "TipoPagamento");
            return View();
        }

        // POST: /Atendimento/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Oid,Codigo,DataInicio,DataFim,CarroOid")] Atendimento atendimento)
        {
            if (ModelState.IsValid)
            {
                atendimento.Codigo = Guid.NewGuid().ToString().Substring(0, 8);

                db.Atendimentos.Add(atendimento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CarroOid = new SelectList(db.Carros, "Oid", "Placa", atendimento.CarroOid);
            ViewBag.Oid = new SelectList(db.Fatura, "Oid", "TipoPagamento", atendimento.Oid);
            return View(atendimento);
        }

        // GET: /Atendimento/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Atendimento atendimento = db.Atendimentos.Find(id);
            if (atendimento == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarroOid = new SelectList(db.Carros, "Oid", "Placa", atendimento.CarroOid);
            ViewBag.Oid = new SelectList(db.Fatura, "Oid", "TipoPagamento", atendimento.Oid);
            return View(atendimento);
        }

        // POST: /Atendimento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Oid,Codigo,DataInicio,DataFim,CarroOid")] Atendimento atendimento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(atendimento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarroOid = new SelectList(db.Carros, "Oid", "Placa", atendimento.CarroOid);
            ViewBag.Oid = new SelectList(db.Fatura, "Oid", "TipoPagamento", atendimento.Oid);
            return View(atendimento);
        }

        // GET: /Atendimento/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Atendimento atendimento = db.Atendimentos.Find(id);
            if (atendimento == null)
            {
                return HttpNotFound();
            }
            return View(atendimento);
        }

        [AllowAnonymous]
        public ActionResult ConsultaUnica(string codigoAtendimento)
        {
            var atendimento = db.Atendimentos.Include(a => a.Fatura).Include(a => a.Carro).FirstOrDefault(a => a.Codigo == codigoAtendimento);
            return View(atendimento);
        }

        // POST: /Atendimento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Atendimento atendimento = db.Atendimentos.Find(id);
            db.Atendimentos.Remove(atendimento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Oficina_codeFirst/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Oficina_codeFirst.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Login()
        {
            ViewBag.Title = "Autenticação";
            return View();
        }
    }
}

Oficina_codeFirst/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Oficina_codeFirst/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Oficina_codeFirst/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/ConsultaClientes.js")"></script>

<div class="jumbotron">
    <h1>Oficina Online</h1>
    <p class="lead">Bem-vindo a aplicação Oficina Online. Desenvolvida como demonstração de conceitos.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Clientes:</h2>
        <p>
            Nesta seção temos as ações disponíveis para clientes:
        </p>
        <form id="consultaAtendimentoForm">
            <input type="text" id="codigoAtendimento" name="codigoAtendimento" />&nbsp;
        </form>
        <p><a class="btn btn-default" id="consultarAtendimentoSubmit" onclick="redirecionar('@Url.Action("ConsultaUnica", "Atendimento")')"> Consultar Atendimento &raquo;</a></p>
    </div>
</div>

Oficina_codeFirst/Views/Home/Login.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet"/>
    <title>Login</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top"> 
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Oficina - Login </a>
            </div>
        </div>
        <div class="container">
            <div class="container">
                <div>
                    <form id="form-login" name="form-login">
                        <p>
                            <label for="txtLogin">Login</label>&nbsp;
                            <input type="text" id="txtLogin" name="txtLogin" />
                        </p>
                        <p>
                            <label for="txtSenha">Senha</label>&nbsp;
                            <input type="password" id="txtSenha" name="txtSenha" />
                        </p>
                        <p><a id="botao-entrar" class="btn btn-success"> Entrar </a></p>
                    </form>
                    <label id="status" class="alert alert-warning"></label>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
    </script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.css")"></script>
    <script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/Autenticacao.js")"></script>
</body>
</html>